version: '3.8'
services:
  streamlit:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app
    networks:
    - databases_store_network
networks:
  databases_store_network:
    external: true