version: '3.8'
services:
  streamlit:
    build: .
    container_name: streamlit_app
    env_file:
    - ../.env 
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app
    networks:
    - store_network
networks:
  store_network:
    external: true