version: '3.8'

services:
  db_online_store:
    image: postgres:13
    container_name: db_online_store
    env_file:
    - ../.env 
    environment:
      POSTGRES_USER: ${ONLINE_STORE_USER}
      POSTGRES_PASSWORD: ${ONLINE_STORE_PASSWORD}
      POSTGRES_DB: ${ONLINE_STORE_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./init-scripts/online_store:/docker-entrypoint-initdb.d
      - ./data/online_store:/var/lib/postgresql/data
    networks:
      - store_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d online_store"]
      interval: 5s
      timeout: 5s
      retries: 5

  db_physical_store:
    image: postgres:13
    container_name: db_physical_store
    env_file:
    - ../.env 
    environment:
      POSTGRES_USER: ${PHYSICAL_STORE_USER}
      POSTGRES_PASSWORD: ${PHYSICAL_STORE_PASSWORD}
      POSTGRES_DB: ${PHYSICAL_STORE_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts/physical_store:/docker-entrypoint-initdb.d
      - ./data/physical_store:/var/lib/postgresql/data
    networks:
      - store_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d physical_store"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
    - ../.env 
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80" 
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db_online_store
      - db_physical_store
    networks:
      - store_network
  
  faker_data_service:
    build:
      context: ./faker-data
      dockerfile: ./Dockerfile
    container_name: faker_data
    env_file:
    - ../.env 
    depends_on:
      db_online_store:
        condition: service_healthy
      db_physical_store:
        condition: service_healthy
    links:
      - db_online_store
      - db_physical_store
    networks:
      - store_network


volumes:
  pgadmin_data:

networks:
  store_network:
    external: true
