version: '3.8'
services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8081:8081"
    volumes:
      - ../apache-airflow/data/model:/app/model:ro
      - ./app/:/app/
    environment:
      MODEL_PATH: /app/model/holt_winters_artifact.pkl
    networks:
    - databases_store_network
    
networks:
  databases_store_network:
    external: true